import fs from 'node:fs'
import path from 'node:path'

const ICON_DIR = path.resolve(process.cwd(), 'tam_diagram')
const OUT = path.resolve(process.cwd(), 'src', 'icons.generated.ts')

const files = [
  'agent.svg',
  'human.svg',
  'storage.svg',
  'common_feature_areas.svg',
  'read_write_modify_both.svg',
  'read_write_modify_single_right.svg',
  'read_write_modify_single_left.svg',
]

function svgDataUri(svgText) {
  // IMPORTANT:
  // draw.io styles are `key=value;key=value;...`.
  // A base64 SVG data URI includes a semicolon (`data:image/svg+xml;base64,...`)
  // which *breaks* the style string. Use URL-encoded UTF-8 instead.
  // diagrams.net supports SVG data URIs with UTF-8 encoding.
  const compact = svgText.replace(/\r?\n/g, '')
  const encoded = encodeURIComponent(compact)
    // Extra safety for quotes which can appear in inline SVG.
    .replace(/'/g, '%27')
    .replace(/"/g, '%22')
  return `data:image/svg+xml,${encoded}`
}

function recolor(svgText, from, to) {
  return svgText.replaceAll(from, to)
}

const iconsLight = {}
const iconsDark = {}
for (const f of files) {
  const p = path.join(ICON_DIR, f)
  if (!fs.existsSync(p)) {
    console.error(`[generate-icons] Missing ${p}`)
    process.exitCode = 1
    continue
  }
  const svg = fs.readFileSync(p, 'utf8')
  const key = f.replace('.svg','')
  // "Light" icon set (dark ink) for light backgrounds
  iconsLight[key] = svgDataUri(svg)

  // "Dark" icon set (light ink) for dark backgrounds.
  // We keep the source SVGs simple and just swap the hard-coded #222 ink.
  const svgDark = recolor(svg, '#222', '#e5e7eb')
  iconsDark[key] = svgDataUri(svgDark)
}

const banner = `// AUTO-GENERATED by scripts/generate-icons.mjs
// Do not edit by hand.
`
const body = `${banner}
export const ICONS_LIGHT = ${JSON.stringify(iconsLight, null, 2)} as const
export const ICONS_DARK = ${JSON.stringify(iconsDark, null, 2)} as const
export type IconKey = keyof typeof ICONS_LIGHT
`
fs.writeFileSync(OUT, body, 'utf8')
console.log(`[generate-icons] Wrote ${OUT}`)
